# Generated by Django 3.0.8 on 2020-07-09 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='posts.commentModel'),
        ),
    ]
