# Generated by Django 3.0.8 on 2020-07-09 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20200709_1056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postmodel',
            name='comment',
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.postModel'),
        ),
    ]
